//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Model.comm {
  using System;
  using System.Collections;
  using System.Collections.Generic;
  using System.ComponentModel;
  using System.CodeDom.Compiler;
  using Eco.ObjectImplementation;
  using Eco.ObjectRepresentation;
  using Eco.Services;
  using Eco.Subscription;
  using Eco.UmlCodeAttributes;
  using Eco.UmlRt;
  
  
  [UmlElement(Id="0a5a94b3-07c2-43b6-a9b5-456a486a1613")]
  [UmlTaggedValue("Eco.TableMapping", "Children")]
  public abstract partial class basetree : App.Model.comm.base_class {
    
    #region *** Constructors ***
    
    [GeneratedCodeAttribute("ECO", "7.0.0.0")]
    protected basetree(Eco.ObjectRepresentation.IEcoServiceProvider serviceProvider) : 
        base(serviceProvider) {
      try {
        this.ObjectCreated();
      }
      catch (System.Exception ) {
        this.Deinitialize(serviceProvider);
        throw;
      }
    }
    
    /// <summary>
    /// For framework internal use only
    /// Constructor public for one reason only; to avoid need for ReflectionPermission in reduced trust
    /// </summary>
    [GeneratedCodeAttribute("ECO", "7.0.0.0")]
    protected basetree(Eco.ObjectImplementation.IContent content) : 
        base(content) {
      this.ObjectFetched();
    }
    
    /// <summary>
    /// Creates an Offline object. Can for example be used by MVC runtime to pass values
    /// This is type equivalent to the eco object in everyway - but has none of the eco services
    /// It does however implement INotifyPropertyChanged and INotifyCollectionChanged
    /// </summary>
    [GeneratedCodeAttribute("ECO", "7.0.0.0")]
    public basetree() {
      this.eco_Content = new EcoOfflineValues();
      this.ObjectCreated();
    }
    
    /// <summary>This method is called when the object has been created the first time (not when loaded from a db)</summary>
    partial void ObjectCreated();
    
    /// <summary>This method is called when the object has been loaded from a db (not when it is created the first time)</summary>
    partial void ObjectFetched();
    
    /// <summary>This method is called before the object is deleted. You can perform custom clean up or prevent the deletion by returning false or throw an exception (preferably EcoObjectDeleteException)</summary>
    partial void PreDelete(ref System.Boolean canDelete);
    
    #endregion *** Constructors ***
    
    #region *** ILoopback implementation ***
    
    [GeneratedCodeAttribute("ECO", "7.0.0.0")]
    public override void set_MemberByIndex(int index, object value) {
      base.set_MemberByIndex(index, value);
    }
    
    [GeneratedCodeAttribute("ECO", "7.0.0.0")]
    public override object get_MemberByIndex(int index) {
      return base.get_MemberByIndex(index);
    }
    
    #endregion *** ILoopback implementation ***
    
    #region *** LoopbackIndex declarations ***
    
    new public struct Eco_LoopbackIndices {
      
      public const int Eco_FirstMember = App.Model.comm.base_class.Eco_LoopbackIndices.Eco_MemberCount;
      
      public const int p_key = Eco_FirstMember;
      
      public const int note = (p_key + 1);
      
      public const int treekey = (note + 1);
      
      public const int key = (treekey + 1);
      
      public const int basetree_parent = (key + 1);
      
      public const int basetree_children = (basetree_parent + 1);
      
      public const int Eco_MemberCount = (basetree_children + 1);
    }
    
    #endregion *** LoopbackIndex declarations ***
    
    [UmlElement(Id="06ac2686-b99a-46b7-9fd4-58b37726318f", Index=Eco_LoopbackIndices.p_key)]
    [UmlTaggedValue("derived", "True")]
    [UmlTaggedValue("Eco.DerivationOCL", "if self.basetree_parent=nil then\r\n\'-1\'\r\nelse\r\nself.basetree_parent.key\r\nendif")]
    [GeneratedCodeAttribute("ECO", "7.0.0.0")]
    public string p_key {
      get {
        return ((string)(this.eco_Content.get_MemberByIndex_OfflineAware(Eco_LoopbackIndices.p_key, typeof(string))));
      }
    }
    
    [UmlElement(Id="51dafb41-a1b3-4157-8e4e-bb7102b0c3f2", Index=Eco_LoopbackIndices.note)]
    [GeneratedCodeAttribute("ECO", "7.0.0.0")]
    public string note {
      get {
        return ((string)(this.eco_Content.get_MemberByIndex_OfflineAware(Eco_LoopbackIndices.note, typeof(string))));
      }
      set {
        this.eco_Content.set_MemberByIndex_OfflineAware(Eco_LoopbackIndices.note, ((object)(value)), "note");
      }
    }
    
    [UmlElement(Id="a8445dae-5376-4b7a-b76b-f59a2506870d", Index=Eco_LoopbackIndices.treekey)]
    [UmlTaggedValue("derived", "True")]
    [UmlTaggedValue("Eco.DerivationOCL", "\r\nif self.basetree_parent->isempty then\r\nself.externalId\r\nelse\r\nself.basetree_par" +
      "ent.externalId+\'_\'+self.externalId\r\nendif\r\n")]
    [GeneratedCodeAttribute("ECO", "7.0.0.0")]
    public string treekey {
      get {
        return ((string)(this.eco_Content.get_MemberByIndex_OfflineAware(Eco_LoopbackIndices.treekey, typeof(string))));
      }
    }
    
    [UmlElement(Id="b8f5ca97-9b82-40c7-a661-4cbbaf97cad0", Index=Eco_LoopbackIndices.key)]
    [UmlTaggedValue("derived", "True")]
    [UmlTaggedValue("Eco.DerivationOCL", "self.externalId\r\n\r\n")]
    [GeneratedCodeAttribute("ECO", "7.0.0.0")]
    public string key {
      get {
        return ((string)(this.eco_Content.get_MemberByIndex_OfflineAware(Eco_LoopbackIndices.key, typeof(string))));
      }
    }
    
    [UmlElement("AssociationEnd", Id="9d0b58f3-8490-4086-9b0b-b21facf1a63e", Index=Eco_LoopbackIndices.basetree_parent)]
    [UmlMetaAttribute("association", typeof(App.Model.App_ModelPackage.basetreebasetree_childrenbasetreebasetree_parent), Index=0)]
    [UmlMetaAttribute("multiplicity", "1")]
    [GeneratedCodeAttribute("ECO", "7.0.0.0")]
    public basetree basetree_parent {
      get {
        return ((basetree)(this.eco_Content.get_MemberByIndex_OfflineAware(Eco_LoopbackIndices.basetree_parent, typeof(basetree))));
      }
      set {
        this.eco_Content.set_MemberByIndex_OfflineAware(Eco_LoopbackIndices.basetree_parent, ((object)(value)), "basetree_parent");
      }
    }
    
    [UmlElement("AssociationEnd", Id="e5619c7a-a417-44e4-8675-4569de9a15d2", Index=Eco_LoopbackIndices.basetree_children)]
    [UmlMetaAttribute("association", typeof(App.Model.App_ModelPackage.basetreebasetree_childrenbasetreebasetree_parent), Index=1)]
    [UmlMetaAttribute("multiplicity", "0..*")]
    [GeneratedCodeAttribute("ECO", "7.0.0.0")]
    public IEcoList<basetree> basetree_children {
      get {
        return ((IEcoList<basetree>)(this.eco_Content.get_MemberByIndex_OfflineAware(Eco_LoopbackIndices.basetree_children, typeof(IEcoList<basetree>))));
      }
    }
  }
}
