//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Model.comm {
  using System;
  using System.Collections;
  using System.Collections.Generic;
  using System.CodeDom.Compiler;
  using Eco.ObjectRepresentation;
  using Eco.ObjectImplementation;
  using Eco.Services;
  using Eco.Subscription;
  using Eco.UmlCodeAttributes;
  using Eco.UmlRt;
  
  
  [UmlElement("Package", Id="e8d854d3-86d4-4ce6-8598-976c251a96a8")]
  [UmlTaggedValue("Eco.ModeledName", "comm")]
  [GeneratedCodeAttribute("ECO", "7.0.0.0")]
  [UmlMetaAttribute("ownedElement", typeof(App.Model.comm.delete_obj))]
  [UmlMetaAttribute("ownedElement", typeof(App.Model.comm.user_role))]
  [UmlMetaAttribute("ownedElement", typeof(App.Model.comm.basetree))]
  [UmlMetaAttribute("ownedElement", typeof(App.Model.comm.user))]
  [UmlMetaAttribute("ownedElement", typeof(App.Model.comm.base_class))]
  [UmlMetaAttribute("ownedElement", typeof(App.Model.comm.roles))]
  [UmlMetaAttribute("ownedElement", typeof(App.Model.comm.dept))]
  [UmlMetaAttribute("ownedElement", typeof(App.Model.comm.menugroup))]
  [UmlMetaAttribute("ownedElement", typeof(App.Model.comm.data_action_log))]
  [UmlMetaAttribute("ownedElement", typeof(App.Model.comm.menuitem))]
  [UmlMetaAttribute("ownedElement", typeof(App.Model.comm.text_list))]
  [UmlMetaAttribute("ownedElement", typeof(App.Model.comm.sys_function))]
  [UmlMetaAttribute("ownedElement", typeof(App.Model.comm.sys_param))]
  public abstract partial class commPackage {
    
    [UmlElement("Association", Id="6c9b94e3-1ab1-4ae3-94aa-930ae693a5a9")]
    [GeneratedCodeAttribute("ECO", "7.0.0.0")]
    public class data_action_logdata_action_logdelete_objdelete_obj {
    }
    
    [UmlElement("Association", Id="815e08de-9830-4ebf-95ca-db224f1bb31b")]
    [GeneratedCodeAttribute("ECO", "7.0.0.0")]
    public class data_action_logdata_action_loguseruser {
    }
    
    [UmlElement("Association", Id="c1ce4a61-8e54-4c00-86da-dccd511f9ed1")]
    [GeneratedCodeAttribute("ECO", "7.0.0.0")]
    public class base_classnonameusercreate_user {
    }
  }
}
