//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Model.comm {
  using System;
  using System.Collections;
  using System.Collections.Generic;
  using System.ComponentModel;
  using System.CodeDom.Compiler;
  using Eco.ObjectImplementation;
  using Eco.ObjectRepresentation;
  using Eco.Services;
  using Eco.Subscription;
  using Eco.UmlCodeAttributes;
  using Eco.UmlRt;
  
  
  [UmlElement(Id="0d14d9b1-acc4-4db1-a5c4-5c2575662fe6")]
  [UmlMetaAttribute("constraint", "constraint-user.username.length-gt=self.Username.Length>0@Error@名称字段值必须大于0@False@" +
    "44414a87-ba82-4f75-b4af-5827b91239c2")]
  [UmlMetaAttribute("constraint", "constraint-user.username.length-lt=self.Username.Length<40@Error@<40@False@84c698" +
    "82-0b90-4f13-a0fd-194f39b8b037")]
  [UmlMetaAttribute("constraint", "constraint-user.email.formate-check=true@Error@@False@9e6ff84f-78b4-40af-a12d-3c5" +
    "3caf5f920")]
  [UmlMetaAttribute("constraint", "constraint-user.sex.value-check=(self.sex>=0) and  (self.sex<2)@Error@@False@a2b2" +
    "b59a-741d-4522-9e0d-0c5908007f45")]
  [UmlMetaAttribute("constraint", "constraint-user.email.length-gt=self.email.Length>0@Error@@False@b7097bd7-9f54-49" +
    "dc-8414-4d819905112b")]
  [UmlMetaAttribute("constraint", "constraint-user.password.length-gt=self.password.length>0@Error@@False@bc977273-9" +
    "ca2-4c94-8aa9-fa30dfe5e360")]
  public partial class user : App.Model.comm.base_class {
    
    #region *** Constructors ***
    
    [GeneratedCodeAttribute("ECO", "7.0.0.0")]
    public user(Eco.ObjectRepresentation.IEcoServiceProvider serviceProvider) : 
        base(serviceProvider) {
      try {
        this.ObjectCreated();
      }
      catch (System.Exception ) {
        this.Deinitialize(serviceProvider);
        throw;
      }
    }
    
    /// <summary>
    /// For framework internal use only
    /// Constructor public for one reason only; to avoid need for ReflectionPermission in reduced trust
    /// </summary>
    [GeneratedCodeAttribute("ECO", "7.0.0.0")]
    public user(Eco.ObjectImplementation.IContent content) : 
        base(content) {
      this.ObjectFetched();
    }
    
    /// <summary>
    /// Creates an Offline object. Can for example be used by MVC runtime to pass values
    /// This is type equivalent to the eco object in everyway - but has none of the eco services
    /// It does however implement INotifyPropertyChanged and INotifyCollectionChanged
    /// </summary>
    [GeneratedCodeAttribute("ECO", "7.0.0.0")]
    public user() {
      this.eco_Content = new EcoOfflineValues();
      this.ObjectCreated();
    }
    
    /// <summary>This method is called when the object has been created the first time (not when loaded from a db)</summary>
    partial void ObjectCreated();
    
    /// <summary>This method is called when the object has been loaded from a db (not when it is created the first time)</summary>
    partial void ObjectFetched();
    
    /// <summary>This method is called before the object is deleted. You can perform custom clean up or prevent the deletion by returning false or throw an exception (preferably EcoObjectDeleteException)</summary>
    partial void PreDelete(ref System.Boolean canDelete);
    
    #endregion *** Constructors ***
    
    #region *** ILoopback implementation ***
    
    [GeneratedCodeAttribute("ECO", "7.0.0.0")]
    public override void set_MemberByIndex(int index, object value) {
      switch(index) {
      case Eco_LoopbackIndices.Password:
      this.Password = ((string)(value));
        break;
      case Eco_LoopbackIndices.Username:
      this.Username = ((string)(value));
        break;
      case Eco_LoopbackIndices.ConfirmPassword:
      this.ConfirmPassword = ((string)(value));
        break;
      case Eco_LoopbackIndices.email:
      this.email = ((string)(value));
        break;
      default:
      base.set_MemberByIndex(index, value);
        break;
      }
    }
    
    [GeneratedCodeAttribute("ECO", "7.0.0.0")]
    public override object get_MemberByIndex(int index) {
      switch(index) {
      case Eco_LoopbackIndices.Password:
      return this.Password;
      case Eco_LoopbackIndices.Username:
      return this.Username;
      case Eco_LoopbackIndices.ConfirmPassword:
      return this.ConfirmPassword;
      case Eco_LoopbackIndices.email:
      return this.email;
      default:
      return base.get_MemberByIndex(index);
      }
    }
    
    #endregion *** ILoopback implementation ***
    
    #region *** LoopbackIndex declarations ***
    
    new public struct Eco_LoopbackIndices {
      
      public const int Eco_FirstMember = App.Model.comm.base_class.Eco_LoopbackIndices.Eco_MemberCount;
      
      public const int Password = Eco_FirstMember;
      
      public const int Username = (Password + 1);
      
      public const int RememberMe = (Username + 1);
      
      public const int education = (RememberMe + 1);
      
      public const int ConfirmPassword = (education + 1);
      
      public const int email = (ConfirmPassword + 1);
      
      public const int birthday = (email + 1);
      
      public const int sex = (birthday + 1);
      
      public const int own_dept = (sex + 1);
      
      public const int noname = (own_dept + 1);
      
      public const int noname2 = (noname + 1);
      
      public const int data_action_log = (noname2 + 1);
      
      public const int my_dept = (data_action_log + 1);
      
      public const int user_role = (my_dept + 1);
      
      public const int Eco_MemberCount = (user_role + 1);
    }
    
    #endregion *** LoopbackIndex declarations ***
    
    [UmlElement(Id="00d786cd-6862-4f57-82df-84717ffd6cb3", Index=Eco_LoopbackIndices.Password)]
    [UmlMetaAttribute("initialValue", "yourpass")]
    [UmlTaggedValue("Eco.HasUserCode", "True")]
    [GeneratedCodeAttribute("ECO", "7.0.0.0")]
    public string Password {
      get {
        this.PasswordReading();
        string res = ((string)(this.eco_Content.get_MemberByIndex_OfflineAware(Eco_LoopbackIndices.Password, typeof(string))));
        this.PasswordRead(ref res);
        return res;
      }
      set {
        string oldValue = this.Password;
        string newValue = value;
        bool abortModification = false;
        this.PasswordChanging(ref value, ref abortModification);
        if (abortModification) {
          return;
        }
        this.eco_Content.set_MemberByIndex_OfflineAware(Eco_LoopbackIndices.Password, ((object)(value)), "Password");
        this.PasswordChanged(oldValue, newValue, value);
      }
    }
    
    [UmlElement(Id="0cb36d0b-1e9a-4205-a498-d0882ba82838", Index=Eco_LoopbackIndices.Username)]
    [UmlMetaAttribute("initialValue", "name")]
    [UmlTaggedValue("Eco.HasUserCode", "True")]
    [GeneratedCodeAttribute("ECO", "7.0.0.0")]
    public string Username {
      get {
        this.UsernameReading();
        string res = ((string)(this.eco_Content.get_MemberByIndex_OfflineAware(Eco_LoopbackIndices.Username, typeof(string))));
        this.UsernameRead(ref res);
        return res;
      }
      set {
        string oldValue = this.Username;
        string newValue = value;
        bool abortModification = false;
        this.UsernameChanging(ref value, ref abortModification);
        if (abortModification) {
          return;
        }
        this.eco_Content.set_MemberByIndex_OfflineAware(Eco_LoopbackIndices.Username, ((object)(value)), "Username");
        this.UsernameChanged(oldValue, newValue, value);
      }
    }
    
    [UmlElement(Id="6711766e-fe57-4374-a9e9-bf0e923b9756", Index=Eco_LoopbackIndices.RememberMe)]
    [UmlMetaAttribute("initialValue", "true")]
    [UmlTaggedValue("persistence", "transient")]
    [GeneratedCodeAttribute("ECO", "7.0.0.0")]
    public bool RememberMe {
      get {
        return ((bool)(this.eco_Content.get_MemberByIndex_OfflineAware(Eco_LoopbackIndices.RememberMe, typeof(bool))));
      }
      set {
        this.eco_Content.set_MemberByIndex_OfflineAware(Eco_LoopbackIndices.RememberMe, ((object)(value)), "RememberMe");
      }
    }
    
    [UmlElement(Id="7dcaf325-9dcc-4c65-b8b3-7a3a39511a07", Index=Eco_LoopbackIndices.education)]
    [GeneratedCodeAttribute("ECO", "7.0.0.0")]
    public string education {
      get {
        return ((string)(this.eco_Content.get_MemberByIndex_OfflineAware(Eco_LoopbackIndices.education, typeof(string))));
      }
      set {
        this.eco_Content.set_MemberByIndex_OfflineAware(Eco_LoopbackIndices.education, ((object)(value)), "education");
      }
    }
    
    [UmlElement(Id="8248fc9e-d041-4bdd-8289-33c4146df569", Index=Eco_LoopbackIndices.ConfirmPassword)]
    [UmlTaggedValue("Eco.HasUserCode", "True")]
    [UmlTaggedValue("persistence", "transient")]
    [GeneratedCodeAttribute("ECO", "7.0.0.0")]
    public string ConfirmPassword {
      get {
        this.ConfirmPasswordReading();
        string res = ((string)(this.eco_Content.get_MemberByIndex_OfflineAware(Eco_LoopbackIndices.ConfirmPassword, typeof(string))));
        this.ConfirmPasswordRead(ref res);
        return res;
      }
      set {
        string oldValue = this.ConfirmPassword;
        string newValue = value;
        bool abortModification = false;
        this.ConfirmPasswordChanging(ref value, ref abortModification);
        if (abortModification) {
          return;
        }
        this.eco_Content.set_MemberByIndex_OfflineAware(Eco_LoopbackIndices.ConfirmPassword, ((object)(value)), "ConfirmPassword");
        this.ConfirmPasswordChanged(oldValue, newValue, value);
      }
    }
    
    [UmlElement(Id="8ae2a270-55e2-4b38-bd7b-9046775f8472", Index=Eco_LoopbackIndices.email)]
    [UmlMetaAttribute("initialValue", "yourname@kk.com")]
    [UmlTaggedValue("Eco.HasUserCode", "True")]
    [GeneratedCodeAttribute("ECO", "7.0.0.0")]
    public string email {
      get {
        this.emailReading();
        string res = ((string)(this.eco_Content.get_MemberByIndex_OfflineAware(Eco_LoopbackIndices.email, typeof(string))));
        this.emailRead(ref res);
        return res;
      }
      set {
        string oldValue = this.email;
        string newValue = value;
        bool abortModification = false;
        this.emailChanging(ref value, ref abortModification);
        if (abortModification) {
          return;
        }
        this.eco_Content.set_MemberByIndex_OfflineAware(Eco_LoopbackIndices.email, ((object)(value)), "email");
        this.emailChanged(oldValue, newValue, value);
      }
    }
    
    [UmlElement(Id="b98d527a-6704-454b-986e-6faea9700b6c", Index=Eco_LoopbackIndices.birthday)]
    [GeneratedCodeAttribute("ECO", "7.0.0.0")]
    public System.DateTime birthday {
      get {
        return ((System.DateTime)(this.eco_Content.get_MemberByIndex_OfflineAware(Eco_LoopbackIndices.birthday, typeof(System.DateTime))));
      }
      set {
        this.eco_Content.set_MemberByIndex_OfflineAware(Eco_LoopbackIndices.birthday, ((object)(value)), "birthday");
      }
    }
    
    [UmlElement(Id="e032ef31-0f69-4420-961c-47ca9a8c646d", Index=Eco_LoopbackIndices.sex)]
    [UmlMetaAttribute("initialValue", "0")]
    [GeneratedCodeAttribute("ECO", "7.0.0.0")]
    public int sex {
      get {
        return ((int)(this.eco_Content.get_MemberByIndex_OfflineAware(Eco_LoopbackIndices.sex, typeof(int))));
      }
      set {
        this.eco_Content.set_MemberByIndex_OfflineAware(Eco_LoopbackIndices.sex, ((object)(value)), "sex");
      }
    }
    
    [UmlElement("AssociationEnd", Id="1b3ec297-2c1a-4cf4-8943-562802c421cd", Index=Eco_LoopbackIndices.own_dept)]
    [UmlMetaAttribute("association", typeof(App.Model.App_ModelPackage.userdept_managerdeptown_dept), Index=0)]
    [UmlMetaAttribute("multiplicity", "0..*")]
    [GeneratedCodeAttribute("ECO", "7.0.0.0")]
    public IEcoList<dept> own_dept {
      get {
        return ((IEcoList<dept>)(this.eco_Content.get_MemberByIndex_OfflineAware(Eco_LoopbackIndices.own_dept, typeof(IEcoList<dept>))));
      }
    }
    
    [UmlElement("AssociationEnd", Id="36b69f5b-5f4c-45dd-b413-1a34753df58f", Index=Eco_LoopbackIndices.noname)]
    [UmlMetaAttribute("association", typeof(commPackage.base_classnonameusercreate_user), Index=1)]
    [UmlMetaAttribute("multiplicity", "0..*")]
    [GeneratedCodeAttribute("ECO", "7.0.0.0")]
    public IEcoList<base_class> noname {
      get {
        return ((IEcoList<base_class>)(this.eco_Content.get_MemberByIndex_OfflineAware(Eco_LoopbackIndices.noname, typeof(IEcoList<base_class>))));
      }
    }
    
    [UmlElement("AssociationEnd", Id="41cd7f5f-562b-4c2c-955a-2e462ea427f4", Index=Eco_LoopbackIndices.noname2)]
    [UmlMetaAttribute("association", typeof(App.Model.App_ModelPackage.userupdate_userbase_classnoname2), Index=0)]
    [UmlMetaAttribute("multiplicity", "0..*")]
    [GeneratedCodeAttribute("ECO", "7.0.0.0")]
    public IEcoList<base_class> noname2 {
      get {
        return ((IEcoList<base_class>)(this.eco_Content.get_MemberByIndex_OfflineAware(Eco_LoopbackIndices.noname2, typeof(IEcoList<base_class>))));
      }
    }
    
    [UmlElement("AssociationEnd", Id="5f0b8e77-263a-4459-836a-c2dd8130481f", Index=Eco_LoopbackIndices.data_action_log)]
    [UmlMetaAttribute("association", typeof(commPackage.data_action_logdata_action_loguseruser), Index=1)]
    [UmlMetaAttribute("multiplicity", "0..*")]
    [GeneratedCodeAttribute("ECO", "7.0.0.0")]
    public IEcoList<data_action_log> data_action_log {
      get {
        return ((IEcoList<data_action_log>)(this.eco_Content.get_MemberByIndex_OfflineAware(Eco_LoopbackIndices.data_action_log, typeof(IEcoList<data_action_log>))));
      }
    }
    
    [UmlElement("AssociationEnd", Id="dada5684-539a-477f-aff4-d38d1c1b1b58", Index=Eco_LoopbackIndices.my_dept)]
    [UmlMetaAttribute("association", typeof(App.Model.App_ModelPackage.deptmy_deptuserdept_allusers), Index=0)]
    [UmlMetaAttribute("multiplicity", "0..*")]
    [GeneratedCodeAttribute("ECO", "7.0.0.0")]
    public IEcoList<dept> my_dept {
      get {
        return ((IEcoList<dept>)(this.eco_Content.get_MemberByIndex_OfflineAware(Eco_LoopbackIndices.my_dept, typeof(IEcoList<dept>))));
      }
    }
    
    [UmlElement("AssociationEnd", Id="f5930890-d968-482c-b110-1bdbaad6922a", Index=Eco_LoopbackIndices.user_role)]
    [UmlMetaAttribute("association", typeof(App.Model.App_ModelPackage.user_roleuser_roleuseruser), Index=1)]
    [UmlMetaAttribute("multiplicity", "0..*")]
    [GeneratedCodeAttribute("ECO", "7.0.0.0")]
    public IEcoList<user_role> user_role {
      get {
        return ((IEcoList<user_role>)(this.eco_Content.get_MemberByIndex_OfflineAware(Eco_LoopbackIndices.user_role, typeof(IEcoList<user_role>))));
      }
    }
    
    #region *** Password partial methods ***
    
    /// <summary>This method is called before the attribute Password is read</summary>
    partial void PasswordReading();
    
    /// <summary>This method is called after Password is read. It is possible to change the value here.</summary>
    partial void PasswordRead(ref string value);
    
    /// <summary>This method is called before Password is modified, it is possible to change the value that is stored here or abort the modification</summary>
    partial void PasswordChanging(ref string value, ref bool abortModification);
    
    /// <summary>This method is called after Password is modified</summary>
    /// <param name="oldValue">This is the value that Password had before the modification</param>
    /// <param name="newValue">This is the value that someone tried to set</param>
    /// <param name="finalValue">This is the value that Password has after the modification</param>
    partial void PasswordChanged(string oldValue, string newValue, string finalValue);
    
    #endregion *** Password partial methods ***
    
    #region *** Username partial methods ***
    
    /// <summary>This method is called before the attribute Username is read</summary>
    partial void UsernameReading();
    
    /// <summary>This method is called after Username is read. It is possible to change the value here.</summary>
    partial void UsernameRead(ref string value);
    
    /// <summary>This method is called before Username is modified, it is possible to change the value that is stored here or abort the modification</summary>
    partial void UsernameChanging(ref string value, ref bool abortModification);
    
    /// <summary>This method is called after Username is modified</summary>
    /// <param name="oldValue">This is the value that Username had before the modification</param>
    /// <param name="newValue">This is the value that someone tried to set</param>
    /// <param name="finalValue">This is the value that Username has after the modification</param>
    partial void UsernameChanged(string oldValue, string newValue, string finalValue);
    
    #endregion *** Username partial methods ***
    
    #region *** ConfirmPassword partial methods ***
    
    /// <summary>This method is called before the attribute ConfirmPassword is read</summary>
    partial void ConfirmPasswordReading();
    
    /// <summary>This method is called after ConfirmPassword is read. It is possible to change the value here.</summary>
    partial void ConfirmPasswordRead(ref string value);
    
    /// <summary>This method is called before ConfirmPassword is modified, it is possible to change the value that is stored here or abort the modification</summary>
    partial void ConfirmPasswordChanging(ref string value, ref bool abortModification);
    
    /// <summary>This method is called after ConfirmPassword is modified</summary>
    /// <param name="oldValue">This is the value that ConfirmPassword had before the modification</param>
    /// <param name="newValue">This is the value that someone tried to set</param>
    /// <param name="finalValue">This is the value that ConfirmPassword has after the modification</param>
    partial void ConfirmPasswordChanged(string oldValue, string newValue, string finalValue);
    
    #endregion *** ConfirmPassword partial methods ***
    
    #region *** email partial methods ***
    
    /// <summary>This method is called before the attribute email is read</summary>
    partial void emailReading();
    
    /// <summary>This method is called after email is read. It is possible to change the value here.</summary>
    partial void emailRead(ref string value);
    
    /// <summary>This method is called before email is modified, it is possible to change the value that is stored here or abort the modification</summary>
    partial void emailChanging(ref string value, ref bool abortModification);
    
    /// <summary>This method is called after email is modified</summary>
    /// <param name="oldValue">This is the value that email had before the modification</param>
    /// <param name="newValue">This is the value that someone tried to set</param>
    /// <param name="finalValue">This is the value that email has after the modification</param>
    partial void emailChanged(string oldValue, string newValue, string finalValue);
    
    #endregion *** email partial methods ***
  }
}
