//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Model.comm {
  using System;
  using System.Collections;
  using System.Collections.Generic;
  using System.ComponentModel;
  using System.CodeDom.Compiler;
  using Eco.ObjectImplementation;
  using Eco.ObjectRepresentation;
  using Eco.Services;
  using Eco.Subscription;
  using Eco.UmlCodeAttributes;
  using Eco.UmlRt;
  
  
  [UmlElement(Id="07638513-c3e8-401e-8c3f-5be8ce2e4456")]
  public partial class user_role : App.Model.comm.base_class {
    
    #region *** Constructors ***
    
    [GeneratedCodeAttribute("ECO", "7.0.0.0")]
    public user_role(Eco.ObjectRepresentation.IEcoServiceProvider serviceProvider) : 
        base(serviceProvider) {
      try {
        this.ObjectCreated();
      }
      catch (System.Exception ) {
        this.Deinitialize(serviceProvider);
        throw;
      }
    }
    
    /// <summary>
    /// For framework internal use only
    /// Constructor public for one reason only; to avoid need for ReflectionPermission in reduced trust
    /// </summary>
    [GeneratedCodeAttribute("ECO", "7.0.0.0")]
    public user_role(Eco.ObjectImplementation.IContent content) : 
        base(content) {
      this.ObjectFetched();
    }
    
    /// <summary>
    /// Creates an Offline object. Can for example be used by MVC runtime to pass values
    /// This is type equivalent to the eco object in everyway - but has none of the eco services
    /// It does however implement INotifyPropertyChanged and INotifyCollectionChanged
    /// </summary>
    [GeneratedCodeAttribute("ECO", "7.0.0.0")]
    public user_role() {
      this.eco_Content = new EcoOfflineValues();
      this.ObjectCreated();
    }
    
    /// <summary>This method is called when the object has been created the first time (not when loaded from a db)</summary>
    partial void ObjectCreated();
    
    /// <summary>This method is called when the object has been loaded from a db (not when it is created the first time)</summary>
    partial void ObjectFetched();
    
    /// <summary>This method is called before the object is deleted. You can perform custom clean up or prevent the deletion by returning false or throw an exception (preferably EcoObjectDeleteException)</summary>
    partial void PreDelete(ref System.Boolean canDelete);
    
    #endregion *** Constructors ***
    
    #region *** ILoopback implementation ***
    
    [GeneratedCodeAttribute("ECO", "7.0.0.0")]
    public override void set_MemberByIndex(int index, object value) {
      base.set_MemberByIndex(index, value);
    }
    
    [GeneratedCodeAttribute("ECO", "7.0.0.0")]
    public override object get_MemberByIndex(int index) {
      return base.get_MemberByIndex(index);
    }
    
    #endregion *** ILoopback implementation ***
    
    #region *** LoopbackIndex declarations ***
    
    new public struct Eco_LoopbackIndices {
      
      public const int Eco_FirstMember = App.Model.comm.base_class.Eco_LoopbackIndices.Eco_MemberCount;
      
      public const int name = Eco_FirstMember;
      
      public const int role_name = (name + 1);
      
      public const int user_name = (role_name + 1);
      
      public const int roles = (user_name + 1);
      
      public const int user = (roles + 1);
      
      public const int Eco_MemberCount = (user + 1);
    }
    
    #endregion *** LoopbackIndex declarations ***
    
    [UmlElement(Id="1d3ee97e-f4c7-4fb3-a4dc-71e91dee27e5", Index=Eco_LoopbackIndices.name)]
    [GeneratedCodeAttribute("ECO", "7.0.0.0")]
    public string name {
      get {
        return ((string)(this.eco_Content.get_MemberByIndex_OfflineAware(Eco_LoopbackIndices.name, typeof(string))));
      }
      set {
        this.eco_Content.set_MemberByIndex_OfflineAware(Eco_LoopbackIndices.name, ((object)(value)), "name");
      }
    }
    
    [UmlElement(Id="2e83858f-6931-465b-9205-5f28b18fd880", Index=Eco_LoopbackIndices.role_name)]
    [UmlTaggedValue("persistence", "transient")]
    [UmlTaggedValue("derived", "True")]
    [UmlTaggedValue("Eco.DerivationOCL", "\r\nif self.user->IsEmpty then\r\n\'\'\r\nelse\r\nself.roles.name\r\nendif")]
    [GeneratedCodeAttribute("ECO", "7.0.0.0")]
    public string role_name {
      get {
        return ((string)(this.eco_Content.get_MemberByIndex_OfflineAware(Eco_LoopbackIndices.role_name, typeof(string))));
      }
    }
    
    [UmlElement(Id="36b21626-639a-49e4-9678-45d02fd332c4", Index=Eco_LoopbackIndices.user_name)]
    [UmlTaggedValue("persistence", "transient")]
    [UmlTaggedValue("derived", "True")]
    [UmlTaggedValue("Eco.DerivationOCL", "if self.user->IsEmpty then\r\n\'\'\r\nelse\r\nself.user.Username\r\nendif")]
    [UmlTaggedValue("Eco.Length", "20")]
    [GeneratedCodeAttribute("ECO", "7.0.0.0")]
    public string user_name {
      get {
        return ((string)(this.eco_Content.get_MemberByIndex_OfflineAware(Eco_LoopbackIndices.user_name, typeof(string))));
      }
    }
    
    [UmlElement("AssociationEnd", Id="c5e051b3-051d-4b75-b39f-d813b991b89c", Index=Eco_LoopbackIndices.roles)]
    [UmlMetaAttribute("association", typeof(App.Model.App_ModelPackage.rolesrolesuser_roleuser_role), Index=0)]
    [UmlMetaAttribute("multiplicity", "0..1")]
    [GeneratedCodeAttribute("ECO", "7.0.0.0")]
    public roles roles {
      get {
        return ((roles)(this.eco_Content.get_MemberByIndex_OfflineAware(Eco_LoopbackIndices.roles, typeof(roles))));
      }
      set {
        this.eco_Content.set_MemberByIndex_OfflineAware(Eco_LoopbackIndices.roles, ((object)(value)), "roles");
      }
    }
    
    [UmlElement("AssociationEnd", Id="f0048243-9ab1-42f2-a043-fdd80ac7f3ef", Index=Eco_LoopbackIndices.user)]
    [UmlMetaAttribute("association", typeof(App.Model.App_ModelPackage.user_roleuser_roleuseruser), Index=0)]
    [UmlMetaAttribute("multiplicity", "0..1")]
    [GeneratedCodeAttribute("ECO", "7.0.0.0")]
    public user user {
      get {
        return ((user)(this.eco_Content.get_MemberByIndex_OfflineAware(Eco_LoopbackIndices.user, typeof(user))));
      }
      set {
        this.eco_Content.set_MemberByIndex_OfflineAware(Eco_LoopbackIndices.user, ((object)(value)), "user");
      }
    }
  }
}
