//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Model {
  using System;
  using System.Collections;
  using System.Collections.Generic;
  using System.CodeDom.Compiler;
  using Eco.ObjectRepresentation;
  using Eco.ObjectImplementation;
  using Eco.Services;
  using Eco.Subscription;
  using Eco.UmlCodeAttributes;
  using Eco.UmlRt;
  
  
  [UmlElement("Package", Id="cc70e87e-8d01-4644-87f9-849f18cb3db4")]
  [UmlTaggedValue("Eco.DefaultSuperClass", "base_class")]
  [UmlTaggedValue("Eco.ModeledName", "App.Model")]
  [GeneratedCodeAttribute("ECO", "7.0.0.0")]
  [UmlMetaAttribute("ownedElement", typeof(App.Model.comm.commPackage))]
  [UmlTaggedValue("Eco.DefaultSuperClass", "base_class")]
  public abstract partial class App_ModelPackage {
    
    [UmlElement("Association", Id="285d1d7b-79d2-41ad-90d7-7d014dbf270b")]
    [GeneratedCodeAttribute("ECO", "7.0.0.0")]
    public class menuitemmenuitemmenugroupmenugroup {
    }
    
    [UmlElement("Association", Id="53c662cc-06e2-4454-a3b5-659ab1dfc10e")]
    [GeneratedCodeAttribute("ECO", "7.0.0.0")]
    public class user_roleuser_roleuseruser {
    }
    
    [UmlElement("Association", Id="747a59c9-81a4-4d1b-83fd-788d13a12e26")]
    [GeneratedCodeAttribute("ECO", "7.0.0.0")]
    public class deptmy_deptuserdept_allusers {
    }
    
    [UmlElement("Association", Id="98755c47-1bb3-455a-9806-b3716a3e9cf7")]
    [GeneratedCodeAttribute("ECO", "7.0.0.0")]
    public class rolesrolesuser_roleuser_role {
    }
    
    [UmlElement("Association", Id="a0774ac9-6b33-47c6-b473-34159f9eab5e")]
    [GeneratedCodeAttribute("ECO", "7.0.0.0")]
    public class userupdate_userbase_classnoname2 {
    }
    
    [UmlElement("Association", Id="abd54141-93f8-4a84-9d89-ebd7e6756a45")]
    [GeneratedCodeAttribute("ECO", "7.0.0.0")]
    public class basetreebasetree_childrenbasetreebasetree_parent {
    }
    
    [UmlElement("Association", Id="c5912d32-fa3a-4c87-98a4-6f0cf95432a5")]
    [GeneratedCodeAttribute("ECO", "7.0.0.0")]
    public class userdept_managerdeptown_dept {
    }
  }
}
